from Sep import *
from config import ProductionConfig

app=create_app(ProductionConfig)


with app.app_context():
	# a=User.query.all()
	# req = '['
	# for i in a:
	# 	req+=f"""User(public_id="{i.public_id}",nom ='{i.nom}',prenom ='{i.prenom}',date_naissance ='{i.date_naissance}',debut_SEP ='{i.debut_SEP}',ntel ='{i.ntel}',sexe ='{i.sexe}',metier ="{i.metier}",loisirs ='{i.loisirs}',ville_residence ='{i.ville_residence}',grand_ville ='{i.grand_ville}',medecin_traitant ='{i.medecin_traitant}',traitement ='{i.traitement}',couvMed ='{i.couvMed}',email ='{i.email}',password ='{i.password}',auth ={i.auth},sep ={i.sep},viewed ={i.viewed},active ={i.active},recovery ='{i.recovery}'),\n"""
	# req+=']'
	# print(req)
	users = [User(public_id="6678b87a-207f-11ed-856c-1aa12d4e7a4f",nom ='Abouzia',prenom ='Chaimaa',date_naissance ='1986-04-13',debut_SEP ='2021',ntel ='0661547080/ 0610101027',sexe ='Féminin',metier ="Responsable administratif Ste informatique ",loisirs ='Sport , voyage, music',ville_residence ='Rabat',grand_ville ='Rabat',medecin_traitant ='Dr ouafaa Mouti',traitement ='Gilenya',couvMed ='CNSS',email ='Chaimaa.abouzia@gmail.com',password ='13@chaimaa',auth =True,sep =True,viewed =True,active =True,recovery ='V8S1VS'),
User(public_id="52f57e62-2090-11ed-856c-1aa12d4e7a4f",nom ='Miss',prenom ='Sb',date_naissance ='1992-03-19',debut_SEP ='2019',ntel ='0662248243',sexe ='Féminin',metier ="Banquière ",loisirs ='Sport ',ville_residence ='Casablanca ',grand_ville ='Casablanca',medecin_traitant ='Dr Midafi Naila ',traitement ='Aubagio',couvMed ='Cmim',email ='Sbouiri@outlook.com',password ='DAvidson1992',auth =True,sep =True,viewed =None,active =True,recovery ='K21V14'),
User(public_id="6209d9cc-2075-11ed-a9d0-1aa12d4e7a4f",nom ='Boumart',prenom ='Imane',date_naissance ='1989-08-10',debut_SEP ='2014',ntel ='0669211655',sexe ='Féminin',metier ="Cadre en industrie pharmaceutique",loisirs ='Danser ',ville_residence ='Casablanca ',grand_ville ='Casablanca',medecin_traitant ='Mr Iraqi ',traitement ='Aucun',couvMed ='Aucun',email ='imaneboumart@hotmail.com',password ='baculovirus',auth =True,sep =True,viewed =True,active =True,recovery ='8TTKNV'),
User(public_id="836b3112-2078-11ed-856c-1aa12d4e7a4f",nom ='Ben zairh',prenom ='Mustapha ',date_naissance ='1997-04-12',debut_SEP ='2021',ntel ='0766555597',sexe ='Masculin',metier ="Étudiant ",loisirs ='Voyage ',ville_residence ='Nancy',grand_ville ='Casablanca',medecin_traitant ='Colombo',traitement ='Ocrevus',couvMed ='Aucun',email ='mustapha.benzairh@gmail.com',password ='stoof_123',auth =True,sep =True,viewed =None,active =True,recovery ='4U9GHC'),
User(public_id="637f4646-2090-11ed-856c-1aa12d4e7a4f",nom ='Ballouki',prenom ='Adel',date_naissance ='1987-12-14',debut_SEP ='2011',ntel ='0667059351',sexe ='Masculin',metier ="Ingenieur informatique",loisirs ='Musiue natation ',ville_residence ='Casablanca',grand_ville ='Casablanca',medecin_traitant ='Professeur Slassi',traitement ='Tysabri',couvMed ='CNSS',email ='Adel.ballouki@gmail.com',password ='Adillevis1*',auth =True,sep =True,viewed =True,active =True,recovery ='I6QXFE'),
User(public_id="dbfb3524-2092-11ed-a9d0-1aa12d4e7a4f",nom ='Elb',prenom ='Soumaya',date_naissance ='1990-12-02',debut_SEP ='',ntel ='0615062164',sexe ='Féminin',metier ="supply chain",loisirs ='Musique',ville_residence ='Marseille',grand_ville ='',medecin_traitant ='',traitement ='',couvMed ='Aucun',email ='Soumaya.elb@hotmail.fr',password ='Maroc2020',auth =True,sep =False,viewed =True,active =True,recovery ='GJ81FX'),
User(public_id="11332f30-20ac-11ed-b6e7-5a5f4e82a263",nom ='Louizi ',prenom ='Asmaa ',date_naissance ='1990-11-29',debut_SEP ='2014',ntel ='0691719400',sexe ='Féminin',metier ="Comptable ",loisirs ='Voyage,lecture ',ville_residence ='Casablanca ',grand_ville ='Casablanca',medecin_traitant ='Docteur Adil Iraqi houssaini ',traitement ='Gilenya',couvMed ='CNSS',email ='louizi.asmaa@gmail.com',password ='29RN3a82',auth =True,sep =True,viewed =True,active =True,recovery ='SSWYJ0'),
User(public_id="367d8396-216d-11ed-816a-a68d2ec5a5f0",nom ='Zian',prenom ='Yousra',date_naissance ='1992-04-20',debut_SEP ='2019',ntel ='0666950099',sexe ='Féminin',metier ="Ingénieur industriel",loisirs ='No longer know',ville_residence ='Tetouan',grand_ville ='Tétouan',medecin_traitant ='Mrani Alia',traitement ='Betaferon',couvMed ='Mutuelle privée',email ='Yousrazian@gmail.com',password ='ibrahim2017',auth =False,sep =True,viewed =True,active =True,recovery ='TN7S1J'),
User(public_id="594c7d4e-2174-11ed-816a-a68d2ec5a5f0",nom ='Mokaddem',prenom ='Sofia',date_naissance ='1988-06-07',debut_SEP ='2015',ntel ='0620767143',sexe ='Féminin',metier ="Cadre",loisirs ='Tout et rien',ville_residence ='Casablanca',grand_ville ='Casablanca',medecin_traitant ='Dr naila midafi',traitement ='Aucun',couvMed ='Aucun',email ='Sofia.mokaddem@gmail.com',password ='bidou33.m',auth =True,sep =True,viewed =True,active =True,recovery ='R3Q38O'),
User(public_id="db9abcfe-2177-11ed-92f8-a68d2ec5a5f0",nom ='Houdou',prenom ='Tarik',date_naissance ='1981-06-13',debut_SEP ='2008',ntel ='0661858353',sexe ='Masculin',metier ="Coordinateur",loisirs ='La marche',ville_residence ='Casablanca',grand_ville ='Casablanca',medecin_traitant ='Mouti',traitement ='Avonex',couvMed ='CNSS',email ='Tarikhoudou@gmail.com',password ='secommeca22',auth =True,sep =True,viewed =True,active =True,recovery ='4H5X6K'),
User(public_id="91948394-2175-11ed-816a-a68d2ec5a5f0",nom ='Touahar ',prenom ='Asmae',date_naissance ='1991-05-14',debut_SEP ='2008',ntel ='0697825216',sexe ='Féminin',metier ="Dentiste ",loisirs ='Yoga ,coloriage, lecture ',ville_residence ='Sidi kacem',grand_ville ='Sidi Kacem',medecin_traitant ='Aucun ',traitement ='Aucun',couvMed ='CNOPS',email ='Asmaetouahar1@gmail.com',password ='asmaeasmae31',auth =True,sep =True,viewed =None,active =True,recovery ='NLP00M'),
User(public_id="d5144226-2175-11ed-816a-a68d2ec5a5f0",nom ='Benriyene',prenom ='Salwa',date_naissance ='1986-09-11',debut_SEP ='2003',ntel ='0664887575',sexe ='Féminin',metier ="Ingénieur d'état en informatique",loisirs ='Randonnées, voyages',ville_residence ='Casablanca',grand_ville ='Casablanca',medecin_traitant ='Dr slassi',traitement ='Avonex',couvMed ='Atlanta sanad',email ='Salwabenriyene@gmail.com',password ='salwa2026',auth =True,sep =True,viewed =True,active =True,recovery ='5V5YLO'),
User(public_id="5e8a7cc0-2179-11ed-816a-a68d2ec5a5f0",nom ='Korich',prenom ='Mohamed nazih',date_naissance ='1991-12-22',debut_SEP ='2018',ntel ='0671245494',sexe ='Masculin',metier ="Employé ",loisirs ='Football',ville_residence ='Tanger',grand_ville ='Tanger',medecin_traitant ='Docteur fadil hicham',traitement ='Tysabri',couvMed ='CNSS',email ='Korichnazih@gmail.com',password ='Nazih123',auth =True,sep =True,viewed =True,active =True,recovery ='GW3ICH'),
User(public_id="0920f04c-217a-11ed-816a-a68d2ec5a5f0",nom ='Bahta ',prenom ='Youssef ',date_naissance ='1994-07-21',debut_SEP ='2013',ntel ='0706853737',sexe ='Masculin',metier ="Commercial ",loisirs ='Cinéphile ',ville_residence ='Casablanca ',grand_ville ='Casablanca',medecin_traitant ='Slassi ',traitement ='Ocrevus',couvMed ='CNSS',email ='youssefbahta@gmail.com',password ='youssef1994',auth =True,sep =True,viewed =None,active =True,recovery ='HAFDY7'),
User(public_id="1eb6c170-217a-11ed-92f8-a68d2ec5a5f0",nom ='Mastour ',prenom ='Abdelmajid ',date_naissance ='1990-06-24',debut_SEP ='2013',ntel ='0614883359',sexe ='Masculin',metier ="Banquier",loisirs ='Divers',ville_residence ='Casablanca ',grand_ville ='Casablanca',medecin_traitant ='Dr. Midafi naila',traitement ='Aucun',couvMed ='Mutuelle privée',email ='Abdelmajid.mastour@hotmail.com',password ='Majido5971130',auth =True,sep =True,viewed =True,active =True,recovery ='D47PXA'),
User(public_id="a0136700-217a-11ed-92f8-a68d2ec5a5f0",nom ='YAALAOUI ',prenom ='Fouad',date_naissance ='1991-10-13',debut_SEP ='2018',ntel ='0677010784',sexe ='Masculin',metier ="Sans",loisirs ='Pêche',ville_residence ='Sidi rahal',grand_ville ='Casablanca',medecin_traitant ='Dr bouchra moutawakil',traitement ='Gilenya',couvMed ='CNSS',email ='Yaalaoui.fouad07@gmail.com',password ='Sepanouir07',auth =True,sep =True,viewed =True,active =True,recovery ='2R3N0F'),
User(public_id="c3157e62-217c-11ed-92f8-a68d2ec5a5f0",nom ='Baïna',prenom ='Mouna',date_naissance ='1985-11-21',debut_SEP ='2018',ntel ='0670287054',sexe ='Féminin',metier ="Femme au foyer",loisirs ='Natation',ville_residence ='Tamesna',grand_ville ='Rabat',medecin_traitant ='Benaaboud bouchra',traitement ='Rebif',couvMed ='CNOPS',email ='mounabaina@gmail.com',password ='malaktahaziad3',auth =True,sep =True,viewed =True,active =True,recovery ='QLTTUL'),
User(public_id="825f37fc-2184-11ed-92f8-a68d2ec5a5f0",nom ='Cherkaoui',prenom ='Oumaima',date_naissance ='1980-01-05',debut_SEP ='2011',ntel ='0600636021',sexe ='Féminin',metier ="Mère au foyer",loisirs ='Sport',ville_residence ='Mohammedia ',grand_ville ='Mohammédia',medecin_traitant ='Iraqui Houssaini Adil',traitement ='Ocrevus',couvMed ='CNOPS',email ='oumaimac80@gmail.com',password ='kamilina80',auth =True,sep =True,viewed =True,active =True,recovery ='GMTPNF'),
User(public_id="06f6ec5a-218d-11ed-8fa2-ee6f8954e473",nom ='Nejjar',prenom ='Oussama',date_naissance ='1974-12-31',debut_SEP ='1975',ntel ='0664344344',sexe ='Masculin',metier ="Employé de banque",loisirs ='.',ville_residence ='Casablanca',grand_ville ='Casablanca',medecin_traitant ='Dr Adil laraqui',traitement ='Ocrevus',couvMed ='Cmim',email ='onejjar@gmail.com',password ='Raja491:',auth =True,sep =True,viewed =True,active =True,recovery ='F2IR3J'),
User(public_id="f1c214d0-2192-11ed-95a8-ee6f8954e473",nom ='Mouti',prenom ='Ouafa',date_naissance ='1972-04-10',debut_SEP ='',ntel ='0667225471',sexe ='Féminin',metier ="Médecin neurologue",loisirs ='Sport',ville_residence ='Rabat',grand_ville ='',medecin_traitant ='',traitement ='',couvMed ='Aucun',email ='ouafamouti@yahoo.fr',password ='Avril1972',auth =False,sep =False,viewed =None,active =True,recovery ='1HE041'),
User(public_id="c7698dae-2196-11ed-95ec-32c2414907b7",nom ='Faroini',prenom ='Wafaa',date_naissance ='1995-05-18',debut_SEP ='2015',ntel ='0607639319',sexe ='Féminin',metier ="Ingenieure genie civil ",loisirs ='Sport',ville_residence ='Casablanca',grand_ville ='Casablanca',medecin_traitant ='Dr. Ilham Slassi',traitement ='Ocrevus',couvMed ='CNSS',email ='wafaa.faroini1@gmail.com',password ='casa101010',auth =True,sep =True,viewed =True,active =True,recovery ='MQ1LV8'),
User(public_id="5ba1f9ec-232d-11ed-bc4c-1ede2e09bfe6",nom ='Gannoune',prenom ='Aziza',date_naissance ='1986-08-24',debut_SEP ='',ntel ='',sexe ='Féminin',metier ="Ingénieur ",loisirs ='Yoga / Vélo ',ville_residence ='Casablanca',grand_ville ='',medecin_traitant ='',traitement ='',couvMed ='',email ='Aziza.gannoune@gmail.com',password ='Azizag86',auth =False,sep =False,viewed =None,active =True,recovery ='FHR6CT'),
User(public_id="159bf19c-237c-11ed-8d12-16ee9eec16fa",nom ='Wahbi mernissi ',prenom ='Mehdi ',date_naissance ='1986-07-09',debut_SEP ='',ntel ='',sexe ='Masculin',metier ="Ingénieur ",loisirs ='Foot',ville_residence ='Casa',grand_ville ='',medecin_traitant ='',traitement ='',couvMed ='Aucun',email ='Wahbi.mehdi@gmail.com',password ='123456789M',auth =False,sep =False,viewed =True,active =False,recovery ='MPW364'),
User(public_id="51e084e2-23f4-11ed-a9d1-368288137520",nom ='Chairi',prenom ='Abderafie',date_naissance ='2002-01-01',debut_SEP ='',ntel ='',sexe ='Masculin',metier ="Prof",loisirs ='Sport',ville_residence ='Fnideq',grand_ville ='',medecin_traitant ='',traitement ='',couvMed ='Aucun',email ='abderafiechairi02@gmail.com',password ='123123123',auth =False,sep =False,viewed =True,active =True,recovery ='914CVB')
]
	i=users[0]
	print(i)
	# db.session.add(i)
	# for i in users:
	# 	db.session.add(i)
	# db.session.commit()
	print('done')